import pg from 'pg';

/**
 * 模拟 Cloudflare D1Database 接口的 Postgres 适配器
 */
export class PostgresD1 {
  private pool: pg.Pool;

  constructor(connectionString: string) {
    this.pool = new pg.Pool({ connectionString });
  }

  prepare(query: string) {
    // 忽略 SQLite 特有的 PRAGMA 语句
    if (query.trim().toUpperCase().startsWith('PRAGMA')) {
      return new PostgresPreparedStatement(this.pool, 'SELECT 1', true);
    }
    return new PostgresPreparedStatement(this.pool, query);
  }

  async batch(statements: PostgresPreparedStatement[]) {
    const results = [];
    // 简单起见，这里按顺序执行。如果是为了原子性，应该使用事务。
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      for (const stmt of statements) {
        results.push(await stmt.runInternal(client));
      }
      await client.query('COMMIT');
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
    return results;
  }

  async exec(query: string) {
    await this.pool.query(query);
    return { count: 0, duration: 0 };
  }
}

class PostgresPreparedStatement {
  private query: string;
  private params: any[] = [];

  constructor(private pool: pg.Pool, query: string, skipTranslation = false) {
    if (skipTranslation) {
      this.query = query;
      return;
    }
    // 预处理 SQL：将 SQLite 的一些特有语法转换为 Postgres
    this.query = query
      .replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP')
      .replace(/AUTOINCREMENT/gi, 'GENERATED BY DEFAULT AS IDENTITY')
      .replace(/ LIKE /gi, ' ILIKE ')
      // 处理 Postgres 索引行大小限制：将长文本列的唯一索引改为 MD5 哈希索引
      .replace(/ON CONFLICT\s*\(\s*subscription_id\s*,\s*name\s*,\s*pattern\s*\)/gi, 
               'ON CONFLICT(subscription_id, name, (md5(pattern)))')
      .replace(/ON CONFLICT\s*\(\s*subscription_id\s*,\s*book_source_url\s*\)/gi, 
               'ON CONFLICT(subscription_id, (md5(book_source_url)))')
      .replace(/CREATE UNIQUE INDEX IF NOT EXISTS idx_rules_unique\s+ON\s+rules\s*\(\s*subscription_id\s*,\s*name\s*,\s*pattern\s*\)/gi,
               'CREATE UNIQUE INDEX IF NOT EXISTS idx_rules_unique ON rules(subscription_id, name, (md5(pattern)))')
      .replace(/CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_unique\s+ON\s+sources\s*\(\s*subscription_id\s*,\s*book_source_url\s*\)/gi,
               'CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_unique ON sources(subscription_id, (md5(book_source_url)))');
  }

  bind(...params: any[]) {
    const stmt = new PostgresPreparedStatement(this.pool, this.query);
    stmt.params = params;
    return stmt;
  }

  private convertQuery() {
    let index = 1;
    return this.query.replace(/\?/g, () => `$${index++}`);
  }

  async all() {
    const res = await this.pool.query(this.convertQuery(), this.params);
    return { results: res.rows, success: true, meta: { duration: 0 } };
  }

  async first(column?: string) {
    const res = await this.pool.query(this.convertQuery(), this.params);
    const row = res.rows[0];
    if (!row) return null;
    return column ? row[column] : row;
  }

  async run() {
    return this.runInternal(this.pool);
  }

  /** 供 batch 内部使用，支持传入 client（事务） */
  async runInternal(executor: pg.Pool | pg.PoolClient) {
    let sql = this.convertQuery();
    
    // 自动为 INSERT 语句添加 RETURNING id 以支持 meta.last_row_id
    const isInsert = sql.trim().toUpperCase().startsWith('INSERT');
    if (isInsert && !sql.toUpperCase().includes('RETURNING')) {
      sql += ' RETURNING id';
    }

    try {
      const res = await executor.query(sql, this.params);
      const lastRowId = res.rows[0]?.id;
      return { 
        success: true, 
        meta: { 
          duration: 0, 
          changes: res.rowCount, 
          last_row_id: lastRowId 
        } 
      };
    } catch (e: any) {
      // 如果 RETURNING id 失败（例如表没有 id 列），回退到原始 SQL 执行
      if (isInsert && e.message.includes('id') && (e.message.includes('does not exist') || e.message.includes('column'))) {
        const res = await executor.query(this.convertQuery(), this.params);
        return { success: true, meta: { duration: 0, changes: res.rowCount } };
      }
      throw e;
    }
  }

  async raw() {
    const res = await this.pool.query(this.convertQuery(), this.params);
    return res.rows.map(row => Object.values(row));
  }
}
