import pg from 'pg';

/**
 * 模拟 Cloudflare D1Database 接口的 Postgres 适配器
 */
export class PostgresD1 {
  private pool: pg.Pool;

  constructor(connectionString: string) {
    this.pool = new pg.Pool({ connectionString });
  }

  prepare(query: string) {
    // 忽略 SQLite 特有的 PRAGMA 语句
    if (query.trim().toUpperCase().startsWith('PRAGMA')) {
      return new PostgresPreparedStatement(this.pool, 'SELECT 1', true);
    }
    return new PostgresPreparedStatement(this.pool, query);
  }

  async batch(statements: PostgresPreparedStatement[]) {
    const results = [];
    // 简单起见，这里按顺序执行。如果是为了原子性，应该使用事务。
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      for (const stmt of statements) {
        results.push(await stmt.runInternal(client));
      }
      await client.query('COMMIT');
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
    return results;
  }

  async exec(query: string) {
    await this.pool.query(query);
    return { count: 0, duration: 0 };
  }
}

class PostgresPreparedStatement {
  private query: string;
  private params: any[] = [];

  constructor(private pool: pg.Pool, query: string, skipTranslation = false) {
    if (skipTranslation) {
      this.query = query;
      return;
    }
    // 预处理 SQL：将 SQLite 的一些特有语法转换为 Postgres
    this.query = query
      .replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP')
      .replace(/AUTOINCREMENT/gi, 'GENERATED BY DEFAULT AS IDENTITY');
  }

  bind(...params: any[]) {
    const stmt = new PostgresPreparedStatement(this.pool, this.query);
    stmt.params = params;
    return stmt;
  }

  private convertQuery() {
    let index = 1;
    return this.query.replace(/\?/g, () => `$${index++}`);
  }

  async all() {
    const res = await this.pool.query(this.convertQuery(), this.params);
    return { results: res.rows, success: true, meta: { duration: 0 } };
  }

  async first(column?: string) {
    const res = await this.pool.query(this.convertQuery(), this.params);
    const row = res.rows[0];
    if (!row) return null;
    return column ? row[column] : row;
  }

  async run() {
    return this.runInternal(this.pool);
  }

  /** 供 batch 内部使用，支持传入 client（事务） */
  async runInternal(executor: pg.Pool | pg.PoolClient) {
    const res = await executor.query(this.convertQuery(), this.params);
    return { success: true, meta: { duration: 0, changes: res.rowCount } };
  }

  async raw() {
    const res = await this.pool.query(this.convertQuery(), this.params);
    return res.rows.map(row => Object.values(row));
  }
}
